In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree

#https://stackoverflow.com/questions/43798377/one-hot-encode-categorical-variables-and-scale-continuous-ones-simultaneouely

In [118]:
df = pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [119]:
inputs = df.drop('salary_more_then_100k',axis=1)
target = df['salary_more_then_100k']

In [120]:
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [121]:
onehotencoder = OneHotEncoder(handle_unknown='ignore',sparse=False)
X_train = onehotencoder.fit_transform(X_train[['company','job','degree']])
X_test = onehotencoder.transform(X_test[['company','job','degree']])

In [123]:
X_train

array([[0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 1., 0.]])

In [127]:
model = tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [128]:
model.score(X_test,y_test)

1.0

In [129]:
model.predict(X_test)

array([0, 0, 1, 1], dtype=int64)

In [11]:
titanic_df = pd.read_csv('titanic.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [12]:
titanic_inputs = titanic_df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked','Survived'],axis=1)
titanic_target = titanic_df['Survived']

In [13]:
titanic_inputs.Age.fillna(titanic_df.Age.median(),inplace=True)

In [14]:
titanic_inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female  28.0  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [15]:
X_train,X_test,y_train,y_test = train_test_split(titanic_inputs,titanic_target,test_size=0.2)

In [17]:
onehotencoder = OneHotEncoder(handle_unknown='error',sparse=False,drop='first')
scaler = StandardScaler()
encoded_columns_tr = onehotencoder.fit_transform(X_train[['Sex']])
encoded_columns_test = onehotencoder.transform(X_test[['Sex']])
scaled_columns_tr = scaler.fit_transform(X_train[['Pclass','Age','Fare']])
scaled_columns_test = scaler.transform(X_test[['Pclass','Age','Fare']])

In [18]:
X_train = np.concatenate([encoded_columns_tr, scaled_columns_tr], axis=1)
X_test = np.concatenate([encoded_columns_test,scaled_columns_test],axis=1)

In [19]:
X_train

array([[ 0.        ,  0.82691178, -0.78131517, -0.49537693],
       [ 0.        ,  0.82691178, -0.55467693, -0.49753059],
       [ 0.        , -0.37709883, -0.93240733, -0.40968919],
       ...,
       [ 1.        ,  0.82691178, -0.32803869, -0.28981152],
       [ 1.        , -0.37709883,  1.03179075, -0.11516215],
       [ 0.        , -0.37709883, -0.32803869, -0.03765504]])

In [21]:
model = tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
model.score(X_test,y_test)

0.7877094972067039